### PR TITLE
combined create-app and create-project scripts into single script

### LINKED ISSUE #6: create-app.sh errors after removal of api app
In following the README for creating your own API I got an error running create-app.sh. After running bin/create-project.sh and creating a new project, the api app is removed, however it is referenced in INSTALLED_APPS after the example-settings have been copied into the new settings.py file. So when you run ./manage.py startapp api in bin/create-app.sh, it errors saying that the api app does not exist.

The obvious solution to this is not copying the example settings over to the new settings.py file until after the app is created. We could create another script for this, but I was also thinking maybe we should just combine create-project.sh and create-app.sh into a single file and run it all at once with the settings copy at the end? Are there cases where you would want to run create-project but not create-app? Any other thoughts on this?

### PR DESCRIPTION
**Pull request by adpeters**
Fixes #6

### CODE REVIEW

**Comment by adpeters** [comment]
So the way I have it run .env, it won't actually export the environment variables, but it will add them as variables to the current script so it has access to them. That way the script won't be altering the current shell environment without you knowing. But you could change this by doing set -a before running the .env file to have all variables declared in it exported.

I'm pretty sure it works as designed for me, the difference between what I did and your test case is that you are running .env in a different process; if you run it in the current process, ". ./.env" then the variables declared in it will be accessible after and echo $PROJECT_NAME should work fine.

**Comment by bhgrant8** [comment]
Ok will check with your comments, missed the extra `. `

**Comment by znmeb** [comment]
Second comment - bin/remove-sample.sh needs execute bits

**Comment by znmeb** [comment]
Third comment: bin/remove_sample.sh is crashing. As we discovered a while back, stuff gets placed in the folder as `root`, and thus there needs to be a `sudo` in the removes. That's kind of iffy - it's host-dependent. It will work on my Linux host and probably on Windows 10 Pro from WSL Ubuntu. I don't know if it will run from the Docker Toolbox "docker-machine" prompt - I don't have one of those to test on.

Does anyone want to test this on a Mac?

**Comment by znmeb** [comment]
Fourth comment: I've "created an API project" - How do I know whether it worked or not? How do I start it up?

**Comment by znmeb** [comment]
Final comment for the night: bin/remove.sh is removing files checked into the repository. This includes `manage.py`. I think the remove needs to be more selective.

**Comment by bhgrant8** [comment]
The intention of this script is to clean the repo and bootstrap a new project. As such it does remove/alter files in the project repo by design. One should not be committing to this repo after it is run.

We can document this process to create an api from this point on if we would like but that would effectively be rewriting the django rest framework guide, maybe a link to this would be better.

Also to confirm, the manage.py file is a generated by django, and makes a reference to the project folder. The create project command would fail if this is not removed.

**Comment by bhgrant8** [comment]
@znmeb, 

so returning to comment 3 re: root and sudo. 

To clarify, this script is meant to run on the host machine not within a docker container itself. 

when it crashed, were you given an error regarding not finding a file or something else? If you run the version in my pr, which provides checks on whether the files exist, do you run into same error?

With that said could you clarify how "I don't know if it will run from the Docker Toolbox "docker-machine" prompt" will impact this script? Is the idea for providing an edge case where someone is basically running this entire setup within docker or something else I am missing?

As this is something that "makes a dev's life easier" by not running things manually vs. "has to run" for the project to function, I would err on the side of documenting some edge situations, provided this functions for most of our volunteers system vs. spending too much time over-engineering to run on every machine

**Comment by znmeb** [comment]
@bhgrant8 I think when I ran the dead_songs example some things got saved in the repo as `root` - there don't seem to be any `root` owned files now.

If the usage steps for a new project are documented:
1. Clone the repo
2. Edit the .env file
3. Run the script
4. Push to a new repo

it will probably work.

Is that the right workflow or am I missing a step?

**Comment by bhgrant8** [comment]
ahh, yeah that may have been it. I would say you have the essentials of the current process

**Comment by znmeb** [comment]
OK - I'm going to try something:

1. Import the repo with a new name.
2. Clone it.
3. Create a project.
4. Copy one of the transportation backup files to Backups
5. Build and start

**Comment by znmeb** [comment]
Here's the test - almost there:
1. Import the repo to my own account as znmeb/examplar-test.
2. Clone it.
3. Edit .env for the ODOT crash data
4. Run `bin/create-api-project.sh`

Notes:
1. It builds both images. So I should have put the backup file in `Backups` before running the script.
2. The API container put a few things in as `root` and so the script crashed.
```
rm: remove write-protected regular file 'odot_crash_data/settings.py'? y
rm: cannot remove 'odot_crash_data/settings.py': Permission denied
znmeb@AlgoCompSynth ~/Projects/examplar-test $ ll
total 92
-rw-r--r-- 1 znmeb znmeb 4692 Apr 14 14:03 README.md
-rw-r--r-- 1 znmeb znmeb 1068 Apr 14 14:03 LICENSE
-rw-r--r-- 1 znmeb znmeb 1191 Apr 14 14:03 .gitignore
-rw-r--r-- 1 znmeb znmeb 2356 Apr 14 14:03 DOCKERFILE.db.development
-rw-r--r-- 1 znmeb znmeb 1084 Apr 14 14:03 DOCKERFILE.api.staging
-rw-r--r-- 1 znmeb znmeb 1088 Apr 14 14:03 DOCKERFILE.api.development
-rw-r--r-- 1 znmeb znmeb 7111 Apr 14 14:03 gunicorn_config.py
-rw-r--r-- 1 znmeb znmeb  865 Apr 14 14:03 development-docker-compose.yml
-rw-r--r-- 1 znmeb znmeb  596 Apr 14 14:03 staging-docker-compose.yml
drwxr-xr-x 2 znmeb znmeb 4096 Apr 14 14:03 requirements
drwxr-xr-x 2 znmeb znmeb 4096 Apr 14 14:03 postgis-scripts
drwxr-xr-x 2 znmeb znmeb 4096 Apr 14 14:03 postgis-root-scripts
drwxr-xr-x 2 znmeb znmeb 4096 Apr 14 14:03 jessie
drwxr-xr-x 2 znmeb znmeb 4096 Apr 14 14:03 bin
-rw-r--r-- 1 znmeb znmeb 1344 Apr 14 14:06 env.sample
-rw-r--r-- 1 znmeb znmeb 1344 Apr 14 14:06 .env
drwxr-xr-x 8 znmeb znmeb 4096 Apr 14 14:09 .git
drwxr-xr-x 2 znmeb znmeb 4096 Apr 14 14:09 Backups
-rwxr-xr-x 1 root  root   547 Apr 14 14:23 manage.py
drwxr-xr-x 3 root  root  4096 Apr 14 14:23 odot_crash_data
drwxr-xr-x 3 root  root  4096 Apr 14 14:23 api
```

I'll retry it with `sudo` in the remove script and the backup file in the right place.

**Comment by bhgrant8** [comment]
doing so you will have the scaffold of an api project and a database. To be clear the create project/api script will not produce a running api with endpoints, models and views. You still need to follow step 6 in the updated readme:

Create your api code. Checkout the [Django Rest Framework Guide](http://www.django-rest-framework.org/) on how to proceed.

That being said, if you run just the remove script and drop in the following parts of our repo, you should have a working project. This will be in the readme update pr.

Parts to drop in once, existing project is removed:

our database backup
manage.py in root of folder
full "api" folder
full "crash_data_api" folder or equiv. if using the passenger sensus
update the .env

**Comment by bhgrant8** [comment]
looking at that stack trace, you are not actually choking the remove script but in the create script, which removes the settings.py that was created within the docker container by the django create project command here:
https://github.com/hackoregon/backend-examplar-2018/blob/5a8da5f669f258f142b3960fe1fdeabe4d302920/bin/create-api-project.sh#L14

and command that is failing:

https://github.com/hackoregon/backend-examplar-2018/blob/5a8da5f669f258f142b3960fe1fdeabe4d302920/bin/create-api-project.sh#L22

**Comment by znmeb** [comment]
@bhgrant8 Ah! So that needs a `sudo`. The commands after it probably do too. But it works on your Mac without the sudo??

**Comment by znmeb** [comment]
Dang - my pushes are coming here - I forgot to reset the origin in my copy :-(

**Comment by bhgrant8** [comment]
works on my machine 😺

**Comment by bhgrant8** [comment]
Thinking a better pattern on this will be remove the auto step, instead,
just pull out the specific changes made as overrides and add a step to
instructions to add an import step at the end of the default steps to pull
in necessary changes. This is fairly standard python pattern, and similar
to what might be done with the project_config.py. these may even be able to
be combined

This would remove the sudo dependency and the need to rely on some sed
magic.

**Comment by znmeb** [comment]
Here's the working script. Let me know if you want me to push it to this branch:

```
$ cat bin/create-api-project.sh 
#! /bin/bash

set -euo pipefail

# Grab environment variables
. ./.env

# Remove sample files and database
bin/remove-sample.sh

# Create django project and api app
docker-compose -f development-docker-compose.yml run api_development /bin/bash -c "django-admin.py startproject $PROJECT_NAME . ; ./manage.py startapp api"

# fix ownership
if [ `uname -s` = "Linux" ]
then
  echo "sudo chown -R `id -u $USER`:`id -g $USER` ."
  sudo chown -R `id -u $USER`:`id -g $USER` .
fi

# Replace newly created settings with the example settings
rm $PROJECT_NAME/settings.py
cp ./bin/example-settings.py $PROJECT_NAME/settings.py

sed -i "s;\<EXAMPLE_PROJECT_NAME\>;$PROJECT_NAME;g" $PROJECT_NAME/settings.py
```

References for the `chown` hack:
* https://stackoverflow.com/questions/3466166/how-to-check-if-running-in-cygwin-mac-or-linux
* https://www.cyberciti.biz/faq/howto-get-group-name-in-linux/

**Comment by adpeters** [comment]
@znmeb  Looks good to me, go ahead and merge it in to this.

**Comment by bhgrant8** [comment]
since it is fixed in next pr, going to approve and merge.

**Comment by znmeb** [comment]
OK ... meanwhile, on the subject of the environment variables, I'm not a big fan of objects having different names in development and staging. I'm okay with passwords and secrets being different, but database and database user names - no. The fewer settings one has to edit, the better.

**Comment by bhgrant8** [comment]
this functionality is being change in regards to the question of a project_config.py. we will go down to only one set of db vars. #13
this functionality is already worked out from last year's projects, going to integrate in my next pr. so gotcha an it is being addressed

**Pull request merged**
