### PR TITLE
Linux host testing

### PR DESCRIPTION
**Pull request by znmeb**
Cleanups - tested on both Transportation Systems backups

Backups/.gitignore: keeps git from trying to version-control the backups. `dead_songs.sql` was already there so it's not affected.

create-api-project.sh:
1. Remove the images before the `docker-compose run`. `docker-compose` will only build them if they're not there already, so if you have them already you won't necessarily get a correct build.
2. Save a log of the database restore so you can be sure it worked.
3. Use `docker-compose down` to stop and remove the containers.
4. Fix the `root` files on a Linux system.
5. Fix the `sed` operation.

env.sample, development-docker-compose.yml:
We only need to create one database user - the one that owns the backup we are restoring.

README-Workflow.md:
Document my Linux host testing workflow on GitHub.

### CODE REVIEW

**Comment by znmeb** [comment]
It looks like there's a conflict - I need to redo this since you merged the other one. I'm closing - will re-open late tonight (10 - ish)

**Comment by bhgrant8** [comment]
there was just an extra line

**Comment by znmeb** [comment]
Re-opening - I don't want to lose the merge conflict indicator just yet

**Comment by bhgrant8** [comment]
so only thing i wanted to address on this is whether removing the images themselves are necessary (docker rmi)?

 Within the create script, the docker run command is only really running commands in the api container. As the instructions have users run a docker-compose build, would this not, rebuild from the cache level only as needed?

mostly, just want to be kind to developers and not have them repull images more then necessary. 

we could actually update the "run" command as follows, adding the --no-deps, and --rm flags, which would not spinup the db container unnecessary and take care of the compose down command:

```
docker-compose -f development-docker-compose.yml run --no-dep api_development /bin/bash -c "django-admin.py startproject $PROJECT_NAME . ; python manage.py startapp api" --rm
```

otherwise this does work fine, and if tests on linux, i'll approve.

**Comment by znmeb** [comment]
I'm heading out the door - be back about ten. I need to think about it, but I think it's a big win if we can eliminate the need for the db_container in the API creation process! Is that possible?

**Comment by adpeters** [comment]
It seems to me that the development db container is useful in two possible situations:
1. As a test database to try loading a backup .sql file and make sure the DRF api application can successfully access it and serve the api.
2. As a local database to load data from raw/original sources into (via Django, R, or any other way), which will then be used to test the DRF application _and_ generate a backup .sql file.

Am I missing other uses? For the purposes of 1, this could probably be done better by a container that aims to replicate the production environment more closely, like the amazon pet container by @znmeb. For the purposes of 2, something like the existing db_development container seem to make sense. But given the discussion in #21, perhaps it is worth thinking about that container in this context&mdash;as a potentially optional service that could belong in this repo (or the given project's api repo) _or_ could belong in a separate repo.

**Comment by BrianHGrant** [comment]
To clarify, this was not saying to eliminate the db_container completely,
just spinning up the resource as part of the initial create script process.

To put it another way, would you need the database container for either of
these two commands:

`django-admin.py startproject $PROJECT_NAME`

`python manage.py startapp api`

otherwise, it could wait to be built until the build command, which is when
the backup is actually copied over into the container and restored. i would
imagine any DRF based data loading would not occur until the container is
actually started as well?

i am rethinking my original zeel for using the postgis dependencies by
default, largely along the same line of less startup time for a developer,
less complications of the default pattern. so moving over to the
"extensions" may make sense.

**Comment by adpeters** [comment]
Ah I misunderstood.

**Comment by znmeb** [comment]
OK - back. I fixed the merge conflict so let me review the plan:
1. We're adding `--no-dep --rm` to the `docker-compose run` - this eliminated spin-up of the database, will build and run the API image to create the project, then remove the container leaving the image. Is that right?
2. I can modify the README - the user doesn't need the backup until database build time?

**Comment by znmeb** [comment]
closing - reopening shortly to merge into staging

**Pull request closed without merging**
