### PR TITLE
rework using production and dev, update readme to document scripts

### PR DESCRIPTION
**Pull request by bhgrant8**
This pr is intended to address issues raised in:

#8, #24, #25 

Does change the current startup commands, but think this should be more understandable/supportable in the long run.

### CODE REVIEW

**Comment by bhgrant8** [comment]
this should wait until after #27 so any merge conflicts can be addressed

**Comment by znmeb** [comment]
I'll test it as soon as I get the other pull request done.

**Comment by adpeters** [comment]
@bhgrant8 One thing I just noticed is `DOCKERFILE.api.production` references `requirements/development.txt` instead of `requirements/production.txt`.

**Comment by znmeb** [comment]
create works, build works, start works in the database container but not the API container:
```
db_development_1   | PostgreSQL init process complete; ready for start up.
db_development_1   | 
db_development_1   | LOG:  database system was shut down at 2018-04-19 21:56:10 UTC
db_development_1   | LOG:  MultiXact member wraparound protections are now enabled
db_development_1   | LOG:  autovacuum launcher started
db_development_1   | LOG:  database system is ready to accept connections
api_development_1  | Postgres is up
api_development_1  | Debug: True
api_development_1  | Collect static files
api_development_1  | Post-processed 'admin/css/vendor/select2/select2.min.css' as 'admin/css/vendor/select2/select2.min.d44571114a90.css'
api_development_1  | Post-processed 'admin/css/vendor/select2/select2.css' as 'admin/css/vendor/select2/select2.3805311d5fc1.css'
api_development_1  | Post-processed 'rest_framework/docs/css/bootstrap.min.css' as 'rest_framework/docs/css/bootstrap.min.30fe75135f50.css'
api_development_1  | Post-processed 'rest_framework/docs/css/font-awesome-4.0.3.css' as 'rest_framework/docs/css/font-awesome-4.0.3.c1e1ea213abf.css'
api_development_1  | Post-processed 'rest_framework/docs/css/base.css' as 'rest_framework/docs/css/base.c1f714975cce.css'
api_development_1  | Post-processed 'rest_framework/docs/css/bootstrap-theme.min.css' as 'rest_framework/docs/css/bootstrap-theme.min.00b93e6ea6fb.css'
api_development_1  | Post-processed 'rest_framework/docs/css/highlight.css' as 'rest_framework/docs/css/highlight.e0e4d973c6d7.css'
api_development_1  | Post-processed 'rest_framework/docs/css/jquery.json-view.min.css' as 'rest_framework/docs/css/jquery.json-view.min.a2e6beeb6710.css'
api_development_1  | Post-processed 'admin/css/base.css' as 'admin/css/base.33897d8d3faf.css'
api_development_1  | Post-processed 'admin/css/forms.css' as 'admin/css/forms.15ebfebbeb3d.css'
api_development_1  | Post-processed 'admin/css/responsive.css' as 'admin/css/responsive.25d98d3909ed.css'
api_development_1  | Post-processed 'admin/css/autocomplete.css' as 'admin/css/autocomplete.781713f30664.css'
api_development_1  | Post-processed 'admin/css/fonts.css' as 'admin/css/fonts.494e4ec545c9.css'
api_development_1  | Post-processed 'admin/css/rtl.css' as 'admin/css/rtl.4c867197b256.css'
api_development_1  | Post-processed 'admin/css/responsive_rtl.css' as 'admin/css/responsive_rtl.2a6652327ccd.css'
api_development_1  | Post-processed 'admin/css/widgets.css' as 'admin/css/widgets.5e372b41c483.css'
api_development_1  | Post-processed 'admin/css/login.css' as 'admin/css/login.a846c0e2ef65.css'
api_development_1  | Post-processed 'admin/css/dashboard.css' as 'admin/css/dashboard.7ac78187c567.css'
api_development_1  | Post-processed 'admin/css/changelists.css' as 'admin/css/changelists.f6dc691f8d62.css'
api_development_1  | Post-processed 'rest_framework/css/bootstrap-tweaks.css' as 'rest_framework/css/bootstrap-tweaks.46ed116b0edd.css'
api_development_1  | Post-processed 'rest_framework/css/default.css' as 'rest_framework/css/default.8d5591a6aabc.css'
api_development_1  | Post-processed 'rest_framework/css/prettify.css' as 'rest_framework/css/prettify.a987f72342ee.css'
api_development_1  | Post-processed 'rest_framework/css/bootstrap.min.css' as 'rest_framework/css/bootstrap.min.86ba6b6fae66.css'
api_development_1  | Post-processed 'rest_framework_swagger/css/reset.css' as 'rest_framework_swagger/css/reset.721a281d7112.css'
api_development_1  | Post-processed 'rest_framework_swagger/css/print.css' as 'rest_framework_swagger/css/print.63fb4dd234b5.css'
api_development_1  | Post-processed 'rest_framework_swagger/css/typography.css' as 'rest_framework_swagger/css/typography.afec03a5ece2.css'
api_development_1  | Post-processed 'rest_framework_swagger/css/screen.css' as 'rest_framework_swagger/css/screen.d57a5ea6edc0.css'
api_development_1  | Post-processed 'admin/css/vendor/select2/select2.min.css' as 'admin/css/vendor/select2/select2.min.d44571114a90.css'
api_development_1  | Post-processed 'admin/css/vendor/select2/select2.css' as 'admin/css/vendor/select2/select2.3805311d5fc1.css'
api_development_1  | Post-processed 'rest_framework/docs/css/bootstrap.min.css' as 'rest_framework/docs/css/bootstrap.min.30fe75135f50.css'
api_development_1  | Post-processed 'rest_framework/docs/css/font-awesome-4.0.3.css' as 'rest_framework/docs/css/font-awesome-4.0.3.c1e1ea213abf.css'
api_development_1  | Post-processed 'rest_framework/docs/css/base.css' as 'rest_framework/docs/css/base.c1f714975cce.css'
api_development_1  | Post-processed 'rest_framework/docs/css/bootstrap-theme.min.css' as 'rest_framework/docs/css/bootstrap-theme.min.00b93e6ea6fb.css'
api_development_1  | Post-processed 'rest_framework/docs/css/highlight.css' as 'rest_framework/docs/css/highlight.e0e4d973c6d7.css'
api_development_1  | Post-processed 'rest_framework/docs/css/jquery.json-view.min.css' as 'rest_framework/docs/css/jquery.json-view.min.a2e6beeb6710.css'
api_development_1  | Post-processed 'admin/css/base.css' as 'admin/css/base.a419cbad388f.css'
api_development_1  | Post-processed 'admin/css/forms.css' as 'admin/css/forms.2003a066ae02.css'
api_development_1  | Post-processed 'admin/css/responsive.css' as 'admin/css/responsive.25d98d3909ed.css'
api_development_1  | Post-processed 'admin/css/autocomplete.css' as 'admin/css/autocomplete.781713f30664.css'
api_development_1  | Post-processed 'admin/css/fonts.css' as 'admin/css/fonts.494e4ec545c9.css'
api_development_1  | Post-processed 'admin/css/rtl.css' as 'admin/css/rtl.4c867197b256.css'
api_development_1  | Post-processed 'admin/css/responsive_rtl.css' as 'admin/css/responsive_rtl.2a6652327ccd.css'
api_development_1  | Post-processed 'admin/css/widgets.css' as 'admin/css/widgets.5e372b41c483.css'
api_development_1  | Post-processed 'admin/css/login.css' as 'admin/css/login.a846c0e2ef65.css'
api_development_1  | Post-processed 'admin/css/dashboard.css' as 'admin/css/dashboard.7ac78187c567.css'
api_development_1  | Post-processed 'admin/css/changelists.css' as 'admin/css/changelists.f6dc691f8d62.css'
api_development_1  | Post-processed 'rest_framework/css/bootstrap-tweaks.css' as 'rest_framework/css/bootstrap-tweaks.46ed116b0edd.css'
api_development_1  | Post-processed 'rest_framework/css/default.css' as 'rest_framework/css/default.8d5591a6aabc.css'
api_development_1  | Post-processed 'rest_framework/css/prettify.css' as 'rest_framework/css/prettify.a987f72342ee.css'
api_development_1  | Post-processed 'rest_framework/css/bootstrap.min.css' as 'rest_framework/css/bootstrap.min.86ba6b6fae66.css'
api_development_1  | Post-processed 'rest_framework_swagger/css/reset.css' as 'rest_framework_swagger/css/reset.721a281d7112.css'
api_development_1  | Post-processed 'rest_framework_swagger/css/print.css' as 'rest_framework_swagger/css/print.63fb4dd234b5.css'
api_development_1  | Post-processed 'rest_framework_swagger/css/typography.css' as 'rest_framework_swagger/css/typography.afec03a5ece2.css'
api_development_1  | Post-processed 'rest_framework_swagger/css/screen.css' as 'rest_framework_swagger/css/screen.d57a5ea6edc0.css'
api_development_1  | Post-processed 'admin/css/vendor/select2/select2.min.css' as 'admin/css/vendor/select2/select2.min.d44571114a90.css'
api_development_1  | Post-processed 'admin/css/vendor/select2/select2.css' as 'admin/css/vendor/select2/select2.3805311d5fc1.css'
api_development_1  | Post-processed 'rest_framework/docs/css/bootstrap.min.css' as 'rest_framework/docs/css/bootstrap.min.30fe75135f50.css'
api_development_1  | Post-processed 'rest_framework/docs/css/font-awesome-4.0.3.css' as 'rest_framework/docs/css/font-awesome-4.0.3.c1e1ea213abf.css'
api_development_1  | Post-processed 'rest_framework/docs/css/base.css' as 'rest_framework/docs/css/base.c1f714975cce.css'
api_development_1  | Post-processed 'rest_framework/docs/css/bootstrap-theme.min.css' as 'rest_framework/docs/css/bootstrap-theme.min.00b93e6ea6fb.css'
api_development_1  | Post-processed 'rest_framework/docs/css/highlight.css' as 'rest_framework/docs/css/highlight.e0e4d973c6d7.css'
api_development_1  | Post-processed 'rest_framework/docs/css/jquery.json-view.min.css' as 'rest_framework/docs/css/jquery.json-view.min.a2e6beeb6710.css'
api_development_1  | Post-processed 'admin/css/base.css' as 'admin/css/base.a419cbad388f.css'
api_development_1  | Post-processed 'admin/css/forms.css' as 'admin/css/forms.2003a066ae02.css'
api_development_1  | Post-processed 'admin/css/responsive.css' as 'admin/css/responsive.25d98d3909ed.css'
api_development_1  | Post-processed 'admin/css/autocomplete.css' as 'admin/css/autocomplete.781713f30664.css'
api_development_1  | Post-processed 'admin/css/fonts.css' as 'admin/css/fonts.494e4ec545c9.css'
api_development_1  | Post-processed 'admin/css/rtl.css' as 'admin/css/rtl.4c867197b256.css'
api_development_1  | Post-processed 'admin/css/responsive_rtl.css' as 'admin/css/responsive_rtl.2a6652327ccd.css'
api_development_1  | Post-processed 'admin/css/widgets.css' as 'admin/css/widgets.5e372b41c483.css'
api_development_1  | Post-processed 'admin/css/login.css' as 'admin/css/login.a846c0e2ef65.css'
api_development_1  | Post-processed 'admin/css/dashboard.css' as 'admin/css/dashboard.7ac78187c567.css'
api_development_1  | Post-processed 'admin/css/changelists.css' as 'admin/css/changelists.f6dc691f8d62.css'
api_development_1  | Post-processed 'rest_framework/css/bootstrap-tweaks.css' as 'rest_framework/css/bootstrap-tweaks.46ed116b0edd.css'
api_development_1  | Post-processed 'rest_framework/css/default.css' as 'rest_framework/css/default.8d5591a6aabc.css'
api_development_1  | Post-processed 'rest_framework/css/prettify.css' as 'rest_framework/css/prettify.a987f72342ee.css'
api_development_1  | Post-processed 'rest_framework/css/bootstrap.min.css' as 'rest_framework/css/bootstrap.min.86ba6b6fae66.css'
api_development_1  | Post-processed 'rest_framework_swagger/css/reset.css' as 'rest_framework_swagger/css/reset.721a281d7112.css'
api_development_1  | Post-processed 'rest_framework_swagger/css/print.css' as 'rest_framework_swagger/css/print.63fb4dd234b5.css'
api_development_1  | Post-processed 'rest_framework_swagger/css/typography.css' as 'rest_framework_swagger/css/typography.afec03a5ece2.css'
api_development_1  | Post-processed 'rest_framework_swagger/css/screen.css' as 'rest_framework_swagger/css/screen.d57a5ea6edc0.css'
api_development_1  | 
api_development_1  | 0 static files copied to '/code/staticfiles', 206 unmodified, 81 post-processed.
api_development_1  | Make migrations
api_development_1  | Traceback (most recent call last):
api_development_1  |   File "./manage.py", line 15, in <module>
api_development_1  |     execute_from_command_line(sys.argv)
api_development_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
api_development_1  |     utility.execute()
api_development_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 365, in execute
api_development_1  |     self.fetch_command(subcommand).run_from_argv(self.argv)
api_development_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 288, in run_from_argv
api_development_1  |     self.execute(*args, **cmd_options)
api_development_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 332, in execute
api_development_1  |     self.check()
api_development_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 364, in check
api_development_1  |     include_deployment_checks=include_deployment_checks,
api_development_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 351, in _run_checks
api_development_1  |     return checks.run_checks(**kwargs)
api_development_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/checks/registry.py", line 73, in run_checks
api_development_1  |     new_errors = check(app_configs=app_configs)
api_development_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/checks/urls.py", line 40, in check_url_namespaces_unique
api_development_1  |     all_namespaces = _load_all_namespaces(resolver)
api_development_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/checks/urls.py", line 57, in _load_all_namespaces
api_development_1  |     url_patterns = getattr(resolver, 'url_patterns', [])
api_development_1  |   File "/usr/local/lib/python3.6/site-packages/django/utils/functional.py", line 36, in __get__
api_development_1  |     res = instance.__dict__[self.name] = self.func(instance)
api_development_1  |   File "/usr/local/lib/python3.6/site-packages/django/urls/resolvers.py", line 536, in url_patterns
api_development_1  |     patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
api_development_1  |   File "/usr/local/lib/python3.6/site-packages/django/utils/functional.py", line 36, in __get__
api_development_1  |     res = instance.__dict__[self.name] = self.func(instance)
api_development_1  |   File "/usr/local/lib/python3.6/site-packages/django/urls/resolvers.py", line 529, in urlconf_module
api_development_1  |     return import_module(self.urlconf_name)
api_development_1  |   File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
api_development_1  |     return _bootstrap._gcd_import(name[level:], package, level)
api_development_1  |   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
api_development_1  |   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
api_development_1  |   File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
api_development_1  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
api_development_1  |   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
api_development_1  |   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
api_development_1  |   File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
api_development_1  | ModuleNotFoundError: No module named '<transportation_systems_passenger_census>'
```

**Comment by bhgrant8** [comment]
could you post you settings.py?

**Comment by znmeb** [comment]
```
$ cat transportation_systems_passenger_census/settings.py 
"""
Django settings for <transportation_systems_passenger_census> project.

Generated by 'django-admin startproject' using Django 2.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG') == "True"

ALLOWED_HOSTS = ['*']


# Application definition

if DEBUG == True:

    INSTALLED_APPS = [
        'django.contrib.admin',
        'django.contrib.auth',
        'django.contrib.contenttypes',
        'django.contrib.sessions',
        'django.contrib.messages',
        'django.contrib.staticfiles',
        'api',
        'corsheaders',
        'django_filters',
        'rest_framework',
        'rest_framework_swagger',
        'test_without_migrations',
        ]

else:
    INSTALLED_APPS = [
        'django.contrib.admin',
        'django.contrib.auth',
        'django.contrib.contenttypes',
        'django.contrib.sessions',
        'django.contrib.messages',
        'django.contrib.staticfiles',
        'api',
        'corsheaders',
        'django_filters',
        'rest_framework',
        'rest_framework_swagger',
        ]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = '<transportation_systems_passenger_census>.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = '<transportation_systems_passenger_census>.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD'),
        'NAME': os.environ.get('POSTGRES_NAME'),
        'USER': os.environ.get('POSTGRES_USER'),
        'HOST': os.environ.get('POSTGRES_HOST'),
        'PORT': os.environ.get('POSTGRES_PORT')
    }
}

if DEBUG == False:

    DATABASES = {
        'default': {
            'ENGINE': 'django_db_geventpool.backends.postgresql_psycopg2',
            'PASSWORD': os.environ.get('POSTGRES_PASSWORD'),
            'NAME': os.environ.get('POSTGRES_NAME'),
            'USER': os.environ.get('POSTGRES_USER'),
            'HOST': os.environ.get('POSTGRES_HOST'),
            'PORT': os.environ.get('POSTGRES_PORT'),
            'CONN_MAX_AGE': 0,
            'OPTIONS': {
                'MAX_CONNS': 20
            }
        }
    }

# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATIC_URL = '/static/'

#custom test runner to toggle between Managed=True and Managed=False for models handling test db
TEST_RUNNER = 'api.utils.UnManagedModelTestRunner'

#rest framework settings for API
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_VERSIONING_CLASS': 'rest_framework.versioning.AcceptHeaderVersioning',
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ),
    'DEFAULT_FILTER_BACKENDS': ('django_filters.rest_framework.DjangoFilterBackend',),
    'TEST_REQUEST_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),
}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
        }
    },
    'loggers': {
        'django.db.backends': {
            'handlers': ['console'],
            'level': 'DEBUG',
        },
    }
}

#add CORS support for all domains
CORS_ORIGIN_ALLOW_ALL = True

```

**Comment by bhgrant8** [comment]
So this is relate to #29 actually, it appears the sed command being used to replace the project name is not including the carrots: "<" and ">" on each end. i think this is probably only on the linux version? not sure though and won't have time to test on mac until later. if the mac command is still my original, it should be working though.

**Pull request merged**
