### PR TITLE
Linux host testing

### PR DESCRIPTION
**Pull request by znmeb**
Revised - tests out fine. Bonus - without the database container and the api image already built it was blindingly fast - under 10 seconds.

### CODE REVIEW

**Comment by znmeb** [comment]
I'm OK with removing the `docker rmi`. What version of `sed` do you have, and what shell are you using? `sed` should be more or less universal. I was getting errors with the one in the script and the one I wrote is the format I've used for a couple of years now. 
```
$ bash --version
GNU bash, version 4.4.19(1)-release (x86_64-unknown-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
$ sed --version
sed (GNU sed) 4.5
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Jay Fenlason, Tom Lord, Ken Pizzini,
and Paolo Bonzini.
GNU sed home page: <https://www.gnu.org/software/sed/>.
General help using GNU software: <https://www.gnu.org/gethelp/>.
E-mail bug reports to: <bug-sed@gnu.org>.
```

**Comment by adpeters** [comment]
I'm on MacOS so that's most likely why it's running differently, using bash version 3.2.57 and sed doesn't exactly have a version on MacOS, since it's just different. I'm not sure if there's a command that will work fine on both systems?

**Comment by znmeb** [comment]
@adpeters The uname check for a Mac is 
```
if [ `uname -s` = "Darwin" ]
then
...
fi
```

I'd rather someone with a Mac make the change - go ahead and do it.

**Comment by znmeb** [comment]
OK - I'm going to merge this. I still want to see the error message on a Mac from my version of the `sed` command though.

**Comment by adpeters** [comment]
@znmeb Okay here's the error I'm getting: 
```
Configuring settings...
sed: 1: "dead_songs/settings.py": extra characters at the end of d command
```

**Comment by bhgrant8** [comment]
i had gotten a similar error on my mac, which is why i had written it in the original fashion. tbh i did not retest after the updates, so probably would have failed for me without the if statement as well.

**Comment by znmeb** [comment]
Why is it configuring "dead_songs/settings.py"? Hasn't that been removed and replaced with the project you're creating?

**Comment by bhgrant8** [comment]
it is then replacing the "<EXAMPLE_PROJECT>" place holder in the example settings file with your actual project name

**Comment by znmeb** [comment]
@bhgrant8 Yes, but it should be updating a freshly-created settings file. For example, the new project is `transportation_systems_ passenger_census`. Are the environment variables still pointing to `dead_songs`?

**Comment by adpeters** [comment]
@znmeb I was just using that project name again as the the new project name, so it was set in my environment variables.

**Pull request merged**
